version: '3.9'

services:
  audio-player:
    container_name: audio-player
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8467:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
