import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import ProvidersWrapper from '@/store/providers-wrapper';
import { ThemeProvider } from '@/components/providers/theme-provider';
import AuthProvider from '@/components/providers/auth-provider';
import { Header } from '@/components/template/header/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('h-[94dvh] w-screen')}>
        <ThemeProvider>
          <ProvidersWrapper>
            <AuthProvider>
              <Header />
              {children}
            </AuthProvider>
          </ProvidersWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
